### PR TITLE
feat: also build images for arm64

### PR DESCRIPTION
**Pull request by b-fein**

### CODE REVIEW

**Comment by b-fein** [comment]
@chrisknedl Can you please check that this works by building the image locally with
```bash
docker build --build-arg JAVA_VERSION=21.0.5 --build-arg JDK_DOWNLOAD_URL=https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.5%2B11/OpenJDK21U-jdk_x64_linux_hotspot_21.0.5_11.tar.gz --build-arg MAVEN_VERSION=3.9.9 --platform linux/arm64 --tag ghcr.io/uni-passau-artemis/artemis-base:21 --tag ghcr.io/uni-passau-artemis/artemis-base:21.0.5 -f ./base/Dockerfile base
```
and then running the image with
```bash
docker run --rm ghcr.io/uni-passau-artemis/artemis-base:21.0.5 java --version
```

That should probably show either `arm64` or `aarch64` somewhere as part of the version string.

**Comment by chrisknedl** [comment]
First of all, thanks a lot for taking the time to implement this 🙏 

Running `docker run --rm ghcr.io/uni-passau-artemis/artemis-base:21.0.5 java --version` 
causes the following error on my machine:
```
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
 %                        
 ```

**Comment by chrisknedl** [comment]
`docker inspect ghcr.io/uni-passau-artemis/artemis-base:21.0.5` returns 
 ```
"Architecture": "arm64",
"Os": "linux",
```
as part of the output, however.

**Comment by chrisknedl** [comment]
This seems to be a problem when `glibc` is missing from the container. Maybe adding the GNU C Library fixes this problem.
I'll try it out later.

**Comment by b-fein** [comment]
Pushed an update that might fix the issue.

**Comment by chrisknedl** [comment]
No error anymore. The output is
```
openjdk 21.0.5 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)
```

**Pull request merged**
